//   ╔═════╦═════╗   ╔───╦═══════╗   ╔═══════╗   ╔═══════╗   ╔════════───╦═══════╗   ╔───────╗   ╔════╗    ╔───╦═════╗
//   ║     ║     ║   ║   ║       ║   ║       ║   ║       ║   ║           ║       ║   ║       ║   ║    ║    ║   ║     ╚═╗
//   ║     ║     ║   ║   ║       │   ║       ║   ║       ║   ║           ║       ║   ║       ║   ║    ║    ║   ║       ║
//   ║     ║     ║   ║   ║       │   ╠═══╦═══╝   ║       ║   ╚═══════╗   ║       ║   ║       ║   ║    ║    ║   ║       ╠── MICROSOUND
//   ║     ║     ║   ║   ║       │   ║   ║       ║       ║           ║   ║       ║   ║       ║   ║    ║    ║   ║       ║
//   ║     ║     ║   ║   ║       ║   ║   ║       ║       ║           ║   ║       ║   ║       ║   ║    ║    ║   ║     ╔═╝
// ──╩─────╩─────╩───╝   ╚═══════╩───╝   ╚════───╩═══════╩───════════╝   ╚═══════╩───╩═══════╩───╝    ╚════╝   ╚═════╝

execute "printf \"╭─── start of interactive log ────────────────── microsound ─── $(stat -c %y /bin/microsound | awk '{print $1}' | sed 's/-/./g') build ───\n│ >>> \"";
expand;
offset-x -300;
offset-y 300;
width 300;
height 300;
which-monitor initial-pointer-monitor;
duration 3000;
use-blur two-pass-box-blur;
increment-percentage 5;
decrement-percentage 5;

set-image           mute 0 0 "/etc/microsound/assets/bars_unfilled.bmp";
set-image-direction mute up-left;
overlay-image       mute 0 0 "/etc/microsound/assets/sound_box.bmp";
overlay-image       mute 0 0 "/etc/microsound/assets/mute.bmp";

set-image           unmute 0 0 "/etc/microsound/assets/bars_unfilled.bmp";
set-image-direction unmute up-left;
overlay-image       unmute 0 0 "/etc/microsound/assets/sound_box.bmp";

set-image           increment 0 0 "/etc/microsound/assets/bars_unfilled.bmp";
set-image-direction increment up-left;
overlay-image       increment 0 0 "/etc/microsound/assets/sound_box.bmp";
overlay-image       increment 0 0 "/etc/microsound/assets/plus.bmp";

set-image           decrement 0 0 "/etc/microsound/assets/bars_unfilled.bmp";
set-image-direction decrement up-left;
overlay-image       decrement 0 0 "/etc/microsound/assets/sound_box.bmp";
overlay-image       decrement 0 0 "/etc/microsound/assets/minus.bmp";

set-image           overlay 0 42 "/etc/microsound/assets/bars_filled.bmp";
set-image-direction overlay down-left;

set-image           alpha-map 0 0 "/etc/microsound/assets/alpha_map.bmp";
set-image-direction alpha-map up-left;

grab-keycode mod-4 69 volume-up;
grab-keycode mod-4 68 volume-down;
grab-keycode mod-4 67 mute;
